### ISSUE TITLE
Output document is cropped both vertically and horizontally

### ISSUE THREAD

**Issue by Wolfbanus** [nico9889/OneNote2XournalppAddon#17] opened 2024-10-18 09:22 UTC
Hi, thanks in advance for the project!
I want to report an issue that i found.
When I export notes with elements that laterally exceed more or less the 100% zoom (so to get a full view I have to reduce the zoom), the exported .xopp file is truncated laterally.

![Schermata del 2024-10-18 11-13-28](https://github.com/user-attachments/assets/29d08fd3-1ead-49af-8226-28571e73a85b)

![Schermata del 2024-10-18 11-14-25](https://github.com/user-attachments/assets/35fde909-e68d-4396-a71d-3d4730cd890c)

The file.xopp is also truncated vertically (not reaches the end of the onenote file).

I'm using the browser Zen (Firefox 130.0) on PopOs 22.04

**Comment by nico9889** [comment] 2024-10-18 10:24
If I'm not wrong you are reporting two issues at once, and it's kind of confusing me.
Let's see if I understood everything correctly:

>  When I export notes with elements that laterally exceed more or less the 100% zoom (so to get a full view I have to reduce the zoom), the exported .xopp file is truncated laterally.

You have a very large notebook, you zoomed it out to have a complete view of it, then you tried to export it and you got a file truncated horizontally.

This maybe a known issue: the add-on doesn't handle the zoom correctly (which I see only know that is completely undocumented, I thought I wrote it at least in the store page... my bad). **To solve this, try to export the document without changing the zoom.**

> The file.xopp is also truncated vertically (not reaches the end of the onenote file).

The second issue is that the file you exported is truncated vertically as well. This maybe another known issue (this time is documented at least on the store page. I'll may add some kind of warning in the add-on window): OneNote loads the document "lazily", or in other words, the document is split in chunks and every chunks is downloaded only when you should see it on your screen. 
The add-on cannot download the document on its own, so **you need to scroll down the page entirely (and then scroll up!) to be sure the document is entirely downloaded before exporting**.


Let me know if the suggestions work, if they do, do not close this issue, I'll try to do something to solve the zoom issue.
I can't do anything about the second issue though, probably with some "black magic" I can download the document without relying on OneNote, but I'm quite sure Microsoft won't like that.

**Comment by Wolfbanus** [comment] 2024-10-18 11:26
Thanks for the quick reply! You understood well.

As recommended, I always scroll down to the bottom of the page and then go back to the top, waiting for everything to load.

Here are the updates:

- Setting the zoom = 100% makes the .xopp file looks better (text boxes are in the right place) and is complete vertically, but is still truncated laterally

**Comment by nico9889** [comment] 2024-10-18 11:53
I expected the opposite result 😅 it's the first time that I hear of document truncated horizontally and honestly I don't have a clue on how to reproduce this bug. Is it ok for you to share the .one file or share the file with me on OneNote?

You can contact me at cws@nico9889.me (**do not add this mail on OneNote, it's just relay mail!**), you can send me the file or ask for the email to add on OneNote (essendo in privato anche in italiano va bene).

**Comment by Wolfbanus** [comment] 2024-10-18 14:09
How to download the .one file from browser?

**Comment by Wolfbanus** [comment] 2024-10-18 14:18
Update:

I tried again to export with zoom = 100% and now it is complete both vertically and horizontally. At this point I don't know why it was truncated horizontally before.
As soon as I can I'll try on other files

**Comment by nico9889** [comment] 2024-10-18 14:24
> How to download the .one file from browser?

As stated by another user here you should access OneDrive instead of OneNote and you should fine the .one file there.
https://github.com/nico9889/OneNote2XournalppAddon/issues/3#issuecomment-1238408833

**But beware, before I forgot that the .one file contains the entire notebook and not just the note you are trying to convert.**

> I tried again to export with zoom = 100% and now it is complete both vertically and horizontally. At this point I don't know why it was truncated horizontally before.

This is a good and a bad news at the same time since the bug it's no longer reproducible it seems... By the way, in the next days I'll probably work on improving the zoom handling, let's see what happens then.

**Comment by nico9889** [comment] 2024-10-19 22:04
I finally somehow managed to get the output correct while zooming in/out.
If you want to try it out you can download a pre-release from here: https://github.com/nico9889/OneNote2XournalppAddon/releases/tag/V1.7.0-rc.

To install it on Firefox you should input `about:debugging` in the address bar, then click on "This Firefox" and then "Load temporary add-on" (or whatever the text is).

Feedback are welcomed.

**Comment by Wolfbanus** [comment] 2024-10-22 10:32
Feedback:
I tested the 1.7.0 pre-release and it works!
Thanks a lot

**Comment by nico9889** [comment] 2024-10-23 11:04
I updated the pre-release, I fixed some bugs during export causing the page being way bigger than expected while exporting while zooming out... The problem is that for some reason it's not fixed on the damn Google Chrome, now it's probably even worse than Firefox before the fixes...

I took the chance to look into the "scroll issue" as well, now it should be possible to export notes without having to scroll to "0,0" before :smiley: 

The only thing remaining, as I said before, it's  fixing Chrome. I'll make some more try to fix it, otherwise I think I'll release it as it is, since all the elements are displayed, ""it's just the page that it's way bigger""" (which may cause rendering issue to Xournal++ if it's too big).

I think I'll be able to upload the final release on the stores and close this issue by the end of this day (UTC +2).

**Closed as completed** 2024-10-23 12:02 UTC
Labels: bug

**Comment by nico9889** [comment] 2024-10-23 12:46
> I updated the pre-release, I fixed some bugs during export causing the page being way bigger than expected while exporting while zooming out... The problem is that for some reason it's not fixed on the damn Google Chrome, now it's probably even worse than Firefox before the fixes...

Apparently it wasn't strictly related with Chrome, the add-on was just exporting the empty text box created by clicking on the document.

> I think I'll be able to upload the final release on the stores and close this issue by the end of this day (UTC +2).

By the way, the extension is now published on Mozilla and it's uploaded on the Chrome Web Store waiting for Google to review it. It can take up to 24h before Google approves the add-on for publishing.
